### ISSUE TITLE
[admin-system] Create /loginto

### ISSUE THREAD

**Issue by ImSkully** [ImSkully/emeraldgamingmta#47]
Manager+ command to log into other player's characters.

**Comment by DisHade** [comment]
`-- /loginto - by Hade (29/06/19) [Manager]
function loginto(thePlayer, commandName, ...)
    if exports.global:isPlayerManager(thePlayer) then
        if not (...) then
        	outputChatBox("SYNTAX: /" .. commandName .. " [Character Name]", thePlayer, 75, 230, 10)
        else
            targetChar = table.concat({...}, "_") 
            local fetchData = exports.mysql:QueryString("SELECT `id` FROM `characters` WHERE `name` = (?);",tostring(targetChar))
            local targetCharID = tonumber(fetchData) 
            local thePlayerName = exports.global:getStaffTitle(thePlayer)
            triggerEvent("character:spawnCharacter",thePlayer,thePlayer,targetCharID)  
            exports.global:sendMessageToManagers("[INFO]: " .. tostring(thePlayerName) .. " logged into character '"..tostring(targetChar).."'.")
        end
    end
end
addCommandHandler("loginto", loginto, false, false)`

**Comment by DisHade** [comment]
-- /loginto - by Hade (29/06/19) [Manager]
function loginto(thePlayer, commandName, ...)
    if exports.global:isPlayerManager(thePlayer) then
        if not (...) then
        	outputChatBox("SYNTAX: /" .. commandName .. " [Character Name]", thePlayer, 75, 230, 10)
        else
            targetChar = table.concat({...}, "_") 
            local fetchData = exports.mysql:QueryString("SELECT `id` FROM `characters` WHERE `name` = (?);",tostring(targetChar))
            local targetCharID = tonumber(fetchData) 
            local thePlayerName = exports.global:getStaffTitle(thePlayer)
            triggerEvent("character:spawnCharacter",thePlayer,thePlayer,targetCharID)  
            exports.global:sendMessageToManagers("[INFO]: " .. tostring(thePlayerName) .. " logged into character '"..tostring(targetChar).."'.")
        end
    end
end
addCommandHandler("loginto", loginto, false, false)

**Comment by DisHade** [comment]
Server side ofc

**Comment by ImSkully** [comment]
Completed in c06c3a6172224d7e3584a883898ce9f9d6fb4a4f.
