### ISSUE TITLE
Source code request for compiled scripts

### ISSUE THREAD

**Issue by botder** [ImSkully/emeraldgamingmta#66]
Hello there.

Can you provide me with the source code for the compiled scripts (3 in total):
- emGUI\code.lua
- emGUI\event.luac
- login-system\s_login.luac

According to your license (GPLv3) you are required to provide the source code.
https://github.com/ImSkully/emeraldgamingmta/blob/29ad5c0fa0a6d74f01d58310edb4c9c511d81ef9/LICENSE#L245-L341

**Comment by ImSkully** [comment]
Hi,

The code was released already but I've just come to notice now that my commit was reverted automatically by my git client to prevent merge issues. This also reverted quite a few features that were implemented - I am working on reverting the 'revert' commit and it should be restored.

**Comment by ImSkully** [comment]
Resolved in https://github.com/ImSkully/emeraldgamingmta/pull/68.

**Comment by botder** [comment]
I can't reproduce the MD5 sum.
```
8b88a6c36613c2ef9de2623e30d6ea1f  s_login.new-commit.luac                                                               8b88a6c36613c2ef9de2623e30d6ea1f  s_login.old-commit.luac                                                               aab22385848d79c840d837518e319c00  s_login.source.ob-level-0.luac                                                        50672a9a883c11f517eb741dbdb84e01  s_login.source.ob-level-1.luac                                                        5250e416855e03daf720a03da8de63ae  s_login.source.ob-level-2.luac
```

**Comment by ImSkully** [comment]
The same file that was released originally is the same file that is back on the master branch now, as displayed by PR #68, this reverted the original revert commit which had removed the `s_login.lua` file.

**Comment by botder** [comment]
I cannot reproduce the MD5 sum for the deleted compiled scripts, which shouldn't happen if there weren't changes made to the files behind the scenes before compilation.

**Comment by ImSkully** [comment]
It's impossible for any changes to occur 'behind the scenes', all changes are tracked via GitHub and you can see this through the files git blame history, it was placed back from it's [revert](https://github.com/ImSkully/emeraldgamingmta/blame/master/login-system/s_login.lua).

Following the git blame back, you can see that the file was added in commit 120e7c4301cba1a60805b378913f61f519634886, removed accidentally in f8d66d430f1fcb6d16ba7f68a90a529462d92874, and then placed back in PR #68. You can even check the branch which contains a snapshot of the repo at the point it was reverted with full history: https://github.com/ImSkully/emeraldgamingmta/tree/revert-64-revert-63-master

**Comment by botder** [comment]
It's not really important for me how you manage your source code. I still request the source code for the other compiled scripts and it doesn't matter if you delete them now or later, because I already got the repository before you undid your commit mistake:
- emGUI\code.lua
- emGUI\event.luac

**Comment by ImSkully** [comment]
You can already find both of these files from the repository.
* [event.lua](https://github.com/ImSkully/emeraldgamingmta/blob/master/emGUI/event.lua) | [event.luac](https://github.com/ImSkully/emeraldgamingmta/blob/9408c8b7682ef1cbca88d2c1e71b2d0cbe587eab/emGUI/event.luac)
* [code.lua](https://github.com/ImSkully/emeraldgamingmta/blob/9408c8b7682ef1cbca88d2c1e71b2d0cbe587eab/emGUI/code.lua)

We do not have the decompiled `code.lua` as this is from the original [**dgs resource**](https://github.com/thisdp/dgs) by thisdp which we forked, the file was discontinued in July, 2017, a long time after this resource was forked and converted into emGUI. You can find the original file from the resource here: https://github.com/thisdp/dgs/commit/db4604fdbbf2b062825a47d1a6d7af6c2ab64e00

**Comment by botder** [comment]
You are free to correct me, but `event.luac` was used as server-side script and the source code in `event.lua` clearly uses client-side only functions - it can't be the source code of `event.luac` and you included both files in meta.xml.
`<script src="event.luac" type="server" />`
`<script src="event.lua" type="client" />`

**Comment by ImSkully** [comment]
`event.luac` is a fake file that was made to house the backdoor, it used the same name as its client-side predecessor simply to make it inconspicuous, in the original dgs resource only `event.lua` exists - this can be seen by the dgs resource as it was two years ago, when it was forked: https://github.com/thisdp/dgs/tree/db4604fdbbf2b062825a47d1a6d7af6c2ab64e00

Just as in the dgs resource state linked above, only `event.lua` existed. I added `event.luac` in a compiled form and made it a serversided script to execute the SQL query that it contained. If you decompile the file, you'll find that it doesn't contain anything related to the dgs resource and is simply the backdoor alone.
